/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xt.yde.thrift.login;


public enum LoginResult implements org.apache.thrift.TEnum {
  ET_UNKNOWN(0),
  ET_TYPE1(1),
  ET_TYPE2(2),
  ET_TYPE3(3),
  ET_TYPE4(4);

  private final int value;

  private LoginResult(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LoginResult findByValue(int value) { 
    switch (value) {
      case 0:
        return ET_UNKNOWN;
      case 1:
        return ET_TYPE1;
      case 2:
        return ET_TYPE2;
      case 3:
        return ET_TYPE3;
      case 4:
        return ET_TYPE4;
      default:
        return null;
    }
  }
}
